export const sample_foods = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  
    {
      id: '7',
      name: 'Green Gram (Moong Dal)',
      price: 80,
      weight: '500g',
      favorite: false,
      origins: ['India'],
      stars: 4.5,
      imageUrl: 'green-gram.jpg',
      tags: ['Grams', 'Dal', 'Vegetarian']
    },
    {
      id: '8',
      name: 'Toor Dal (Pigeon Pea)',
      price: 90,
      weight: '500g',
      favorite: false,
      origins: ['India'],
      stars: 4.2,
      imageUrl: 'toor-dal.jpg',
      tags: ['Grams', 'Dal', 'Vegetarian']
    },
    {
      id: '9',
      name: 'Sugar (Sakkarai)',
      price: 40,
      weight: '1kg',
      favorite: false,
      origins: ['India'],
      stars: 4.8,
      imageUrl: 'sugar.jpg',
      tags: ['Sweetener', 'Cooking', 'Essential']
    },
    {
      id: '10',
      name: 'Chana Dal (Bengal Gram)',
      price: 85,
      weight: '500g',
      favorite: false,
      origins: ['India'],
      stars: 4.3,
      imageUrl: 'chana-dal.jpg',
      tags: ['Grams', 'Dal', 'Vegetarian']
    },
    {
      id: '11',
      name: 'Red Rice',
      price: 100,
      weight: '1kg',
      favorite: false,
      origins: ['India'],
      stars: 4.7,
      imageUrl: 'red-rice.jpg',
      tags: ['Rice', 'Staple', 'Vegetarian']
    },
    {
      id: '12',
      name: 'Brinjal (Eggplant)',
      price: 30,
      weight: '500g',
      favorite: false,
      origins: ['India'],
      stars: 4.0,
      imageUrl: 'brinjal.jpg',
      tags: ['Vegetables', 'Fresh']
    },
    {
      id: '13',
      name: 'Coconut (Fresh)',
      price: 40,
      weight: '1pc',
      favorite: false,
      origins: ['India'],
      stars: 4.5,
      imageUrl: 'coconut.jpg',
      tags: ['Fruits', 'Fresh']
    },
    {
      id: '14',
      name: 'Tamarind (Imli)',
      price: 50,
      weight: '200g',
      favorite: false,
      origins: ['India'],
      stars: 4.4,
      imageUrl: 'tamarind.jpg',
      tags: ['Condiments', 'Cooking']
    },
    {
      id: '15',
      name: 'Turmeric (Haldi)',
      price: 60,
      weight: '100g',
      favorite: false,
      origins: ['India'],
      stars: 4.9,
      imageUrl: 'turmeric.jpg',
      tags: ['Spices', 'Cooking', 'Essential']
    },
    {
      id: '16',
      name: 'Ginger (Adrak)',
      price: 40,
      weight: '200g',
      favorite: false,
      origins: ['India'],
      stars: 4.6,
      imageUrl: 'ginger.jpg',
      tags: ['Spices', 'Fresh']
    },
    {
      id: '17',
      name: 'Coriander Leaves (Cilantro)',
      price: 20,
      weight: '100g',
      favorite: false,
      origins: ['India'],
      stars: 4.8,
      imageUrl: 'coriander.jpg',
      tags: ['Herbs', 'Fresh']
    },
    {
      id: '18',
      name: 'Carrot',
      price: 30,
      weight: '500g',
      favorite: false,
      origins: ['India'],
      stars: 4.2,
      imageUrl: 'carrot.jpg',
      tags: ['Vegetables', 'Fresh']
    }
    
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];
